version: "3.9"

services:
  api:
    image: rust-basic-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL:?DATABASE_URL must be set}
      SERVER_PORT: ${SERVER_PORT:-3000}
      RUST_LOG: ${RUST_LOG:-info}
    ports:
      - "${SERVER_PORT:-3000}:3000"
