[package]
name = "rust-basic-api"
version = "0.1.0"
edition = "2021"


[features]
default = []
test-utils = ["url"]

[dependencies]
anyhow = "1.0"
axum = "0.6.0"
dotenv = "0.15"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.6", features = ["runtime-tokio-rustls", "postgres", "chrono", "json", "macros", "migrate"] }
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
url = { version = "2", optional = true }

[dev-dependencies]
tower = { version = "0.4", features = ["util"] }
hyper = "0.14"
serial_test = "3.0"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
