version: "3.9"

services:
  api:
    build:
      context: .
    image: rust-basic-api:latest
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SERVER_HOST: ${SERVER_HOST:-0.0.0.0}
      SERVER_PORT: ${SERVER_PORT:-3000}
      RUST_LOG: ${RUST_LOG:-info}
    ports:
      - "${SERVER_PORT:-3000}:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app_db}
      POSTGRES_USER: ${POSTGRES_USER:-app_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change_me}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
