version: "3.9"

services:
  app:
    build:
      context: .
    image: rust-basic-api:latest
    ports:
      - "${SERVER_PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_MAX_CONNECTIONS: ${DATABASE_MAX_CONNECTIONS:-5}
      SERVER_PORT: ${SERVER_PORT:-3000}
      RUST_LOG: ${RUST_LOG:-info}
