---
# Requirements configuration for Solana Trading Platform
# This file applies to ALL tasks in the project automatically
# Located at: docs/requirements.yaml (project-level configuration)

# Static environment variables (non-secret configuration)
environment:
  # Logging
  RUST_LOG: "debug"

  # Database Configuration (Kubernetes services in databases namespace)
  # Connectivity: Redis ✅, PostgreSQL ✅, QuestDB ✅ (ILP HTTP & PostgreSQL wire)
  DATABASE_URL: >-
    postgresql://postgres:BSLqLzbtuR4IPUFwXGZ5ne1Lxb74OeVVGhASxCFzk817z6wIJRWIGKqLm2uaDX3w@test-db.databases.svc.cluster.local:5432/postgres
