name: Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-rust:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./rust-basic-api
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: rust-basic-api -> target
          shared-key: rust-cache-ci
      - name: Format check
        run: cargo fmt --all -- --check
      - name: Clippy pedantic (zero tolerance)
        run: cargo clippy --all-targets --all-features -- -D warnings -W clippy::pedantic

  test-rust:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./rust-basic-api
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: rust-basic-api -> target
          shared-key: rust-cache-ci
      - name: Run tests
        run: cargo test --all-features --all-targets

  coverage-rust:
    runs-on: ubuntu-22.04
    continue-on-error: true
    defaults:
      run:
        working-directory: ./rust-basic-api
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: llvm-tools-preview
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: rust-basic-api -> target
          shared-key: rust-cache-ci
      - name: Install cargo-llvm-cov
        run: cargo install cargo-llvm-cov --force
      - name: Test coverage (informational only)
        run: cargo llvm-cov --all-features || true
