name: Deploy
on:
  push:
    branches: [main, develop, feature/*, feat/*, fix/*]

env:
  REGISTRY: ghcr.io
  IMAGE_BASE: ghcr.io/5dlabs/rust-basic-api

jobs:
  build:
    runs-on: [k8s-runner]
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: ./rust-basic-api
    steps:
      - uses: actions/checkout@v4
      - name: Build binary
        env:
          RUSTC_WRAPPER: sccache
        run: |
          export CARGO_TARGET_DIR=$HOME/cache/target
          cargo build --release
          cp $CARGO_TARGET_DIR/release/rust-basic-api ./rust-basic-api
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./rust-basic-api
          file: ./rust-basic-api/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/5dlabs/rust-basic-api:latest
            ghcr.io/5dlabs/rust-basic-api:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max