name: YAML Lint

on:
  push:
    branches: [main, 'feature/**']
  pull_request:
    branches: [main]

jobs:
  yamllint:
    name: YAML Lint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install yamllint
        run: pip install yamllint

      - name: Run yamllint
        run: |
          find . -name "*.yml" -o -name "*.yaml" | \
            xargs yamllint -d "{extends: default, rules: {line-length: {max: 120}, document-start: disable}}"
